/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.nvlled;

import javax.swing.*;
import java.text.*;

/**
 *
 * @author nvlled
 */
public class ConversionForm extends javax.swing.JFrame {

    BaseConv baseConv = new BaseConv();

    /**
     * Creates new form MainForm
     */
    public ConversionForm() {
        initComponents();
        
        // initialize comboboxes

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOut2 = new javax.swing.JTextField();
        cmbBaseIn = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtOut8 = new javax.swing.JTextField();
        txtOut16 = new javax.swing.JTextField();
        txtOut10 = new javax.swing.JTextField();
        txtOutN = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cmbBaseOut = new javax.swing.JComboBox<>();
        txtErr1 = new javax.swing.JLabel();
        txtErr2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
        });

        jLabel1.setText("Binary (2):");

        jLabel2.setText("Octal (8):");

        jLabel3.setText("Hexadecimal (16):");

        jLabel4.setText("Decimal (10):");

        jLabel5.setText("Base");

        txtOut2.setEditable(false);

        cmbBaseIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "8", "10", "16", "32", "64", "3", "4", "5", "12" }));
        cmbBaseIn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBaseInItemStateChanged(evt);
            }
        });
        cmbBaseIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBaseInMouseClicked(evt);
            }
        });
        cmbBaseIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbBaseInPropertyChange(evt);
            }
        });
        cmbBaseIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbBaseInKeyReleased(evt);
            }
        });

        jLabel7.setText("Base:");

        txtOut8.setEditable(false);

        txtOut16.setEditable(false);

        txtOut10.setEditable(false);

        txtOutN.setEditable(false);

        cmbBaseOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "8", "10", "16", "32", "64", "3", "4", "5", "12" }));
        cmbBaseOut.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBaseOutItemStateChanged(evt);
            }
        });

        txtErr1.setForeground(new java.awt.Color(255, 51, 0));
        txtErr1.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBaseOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOut2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                            .addComponent(txtOut8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOut16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOut10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOutN, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtErr1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(cmbBaseIn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInput)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbBaseIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOut8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOut16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOut10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOutN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBaseOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErr2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
        doTheThing();
    }//GEN-LAST:event_txtInputKeyReleased

    private void cmbBaseInItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBaseInItemStateChanged
        doTheThing();
    }//GEN-LAST:event_cmbBaseInItemStateChanged

    private void cmbBaseInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbBaseInKeyReleased
  
    }//GEN-LAST:event_cmbBaseInKeyReleased

    private void cmbBaseInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbBaseInPropertyChange
       doTheThing();
    }//GEN-LAST:event_cmbBaseInPropertyChange

    private void cmbBaseInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBaseInMouseClicked
        doTheThing();
    }//GEN-LAST:event_cmbBaseInMouseClicked

    private void cmbBaseOutItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBaseOutItemStateChanged
        doTheThing();
    }//GEN-LAST:event_cmbBaseOutItemStateChanged

    private void doTheThing() {
        txtErr1.setText("");
        txtErr2.setText("");

        int baseIn = Integer.parseInt(cmbBaseIn.getSelectedItem().toString());
        int baseOut = Integer.parseInt(cmbBaseOut.getSelectedItem().toString());

        
        if (!baseConv.isValid(baseIn, txtInput.getText())) {
            txtErr1.setText("invalid char/digit in input");
            clearOutput();
            return;
        }
        

        double x = baseConv.toDecimal(baseIn, txtInput.getText());
        txtOut2.setText(baseConv.fromDecimal(2, x));
        txtOut8.setText(baseConv.fromDecimal(8, x));
        txtOut16.setText(baseConv.fromDecimal(16, x));
        txtOut10.setText(baseConv.fromDecimal(10, x));
        txtOutN.setText(baseConv.fromDecimal(baseOut, x));

    }
    
    private void clearOutput() {
        txtOut2.setText("");
        txtOut8.setText("");
        txtOut10.setText("");
        txtOut16.setText("");
        txtOutN.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBaseIn;
    private javax.swing.JComboBox<String> cmbBaseOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtErr1;
    private javax.swing.JLabel txtErr2;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOut10;
    private javax.swing.JTextField txtOut16;
    private javax.swing.JTextField txtOut2;
    private javax.swing.JTextField txtOut8;
    private javax.swing.JTextField txtOutN;
    // End of variables declaration//GEN-END:variables
}
